services:
  backend:
    image: blelia/aws-workshop:backend-${SERVICE_VERSION}
    build:
      dockerfile: backend/Dockerfile
      context: .
    ports:
      - 8000:8000
    env_file: .env
    restart: unless-stopped

  frontend:
    image: blelia/aws-workshop:frontend-${SERVICE_VERSION}
    build:
      dockerfile: frontend/Dockerfile
      context: .
    ports:
      - 80:80
    env_file: .env
    restart: unless-stopped
