services:
  backend:
    image: blelia/aws-workshop-backend:0.0.1
    build:
      dockerfile: backend/Dockerfile
      context: .
    ports:
      - 8000:8000
    env_file: .env
    restart: unless-stopped

  frontend:
    image: blelia/aws-workshop-frontend:0.0.1
    build:
      dockerfile: frontend/Dockerfile
      context: .
    ports:
      - 80:80
    env_file: .env
    restart: unless-stopped
